### ISSUE TITLE
Does the plugin support apache username and password authentication?

### ISSUE THREAD

**Issue by bryankennedy** [MeetMe/newrelic-plugin-agent#114]
Hi,

I am trying to configure this plugin to report my Apache server-status. I can get the plugin running without any "errors" but after polling the script always just says that there is no data to send along to New Relic.

```
Done, will send remainder of 0 metrics
```

My server-status page is behind a http-authentication, so I'm wondering if the plugin doesn't support that. I've tried a few variations in the YAML cfg file, but none of them seem to work. For what it's worth, I have enabled the extended status, and can curl my server status page with:

```
curl https://username:password@domain.example.org/server-status
```

Here's my latest configuration block:

```
apache_httpd:
   name: Website
   scheme: https
   host: domain.example.org
   verify_ssl_cert: false
   port: 443
   path: /server-status
   username: username
   password: password
```

I've also tried:

```
apache_httpd:
   name: Website
   scheme: https
   host: username:password@domain.example.org
   verify_ssl_cert: false
   port: 443
   path: /server-status
```

Thanks for any help you might be able to provide. Let me know if I've missed something in the documentation.
