### ISSUE TITLE
Support for custom plugins without re-packaging?

### ISSUE THREAD

**Issue by rcoup** [MeetMe/newrelic-plugin-agent#119]
Currently [`NewRelicPluginAgent.start_plugin_polling()`](https://github.com/MeetMe/newrelic-plugin-agent/blob/master/newrelic_plugin_agent/agent.py#L228) looks in `newrelic_plugin_agent.plugins.available` for the list of available plugin keys.

For a user to have an app-specific plugin they'd need to mess with that available list... maybe via monkeypatching or forks or repackaging or something else.

Seems like it'd be pretty easy to support custom plugins in the existing scheme though. My current ideas:
1. plugin names that are fully-qualified class paths:
   
   ```
   Application:
     license_key: REPLACE_WITH_REAL_KEY
     poll_interval: 60
   
     apache_httpd:
       - name: hostname1
         scheme: http
         host: localhost
   
     customapp.newrelic_plugins.foo_app.Foo:
       - name: hostname1
         host: localhost
         foo: bar
   ```
2. an additional mapping of custom plugin names:
   
   ```
   Application:
     license_key: REPLACE_WITH_REAL_KEY
     poll_interval: 60
     custom_plugins:
       - foo_app: customapp.newrelic_plugins.foo_app.Foo
   
     apache_httpd:
       - name: hostname1
         scheme: http
         host: localhost
   
     foo_app:
       - name: hostname1
         host: localhost
         foo: bar
   ```

Happy to code either (or something else) up, just after your views on what the best approach is?
