### ISSUE TITLE
Agent exceeds Max Retries when trying to send data to New Relic behind a proxy

### ISSUE THREAD

**Issue by lawsonj2019** [MeetMe/newrelic-plugin-agent#132]
On an Ubuntu machine behind a proxy I am having issues using the agent for RabbitMQ. The agent appears to be collecting data, but does not seem able to send it to the servers.

I have tried with and without the proxy setting and already have http_proxy and https_proxy environment variables.

If I switch on debugging and grab the body content (switching ' for " in the json) I am able to send the same data successfully to New Relic via CURL.

The error message shown in the logs is...

```
ERROR      2013-08-22 15:27:03 26333  MainProcess     MainThread newrelic_plugin_agent.agent                   send_components           L226   : Error reporting stats: HTTPConnectionPool(host='proxy', port=80): Max retries exceeded with url: https://platform-api.newrelic.com/platform/v1/metrics (Caused by <class 'socket.error'>: [Errno 104] Connection reset by peer)
```

..and on the Proxy we can see a 400 returned by New Relic.

Configuration file is as follows (removing the standard daemon and logging sections)

```
%YAML 1.2

---
Application:
  license_key: redacted
  poll_interval: 60

  rabbitmq:
    name: rabbitmq@myhostname
    host: myhostname
    port: 15672
    username: user
    password: pass
```
