### ISSUE TITLE
MongoDB admin authentication failing

### ISSUE THREAD

**Issue by igoratencompass** [MeetMe/newrelic-plugin-agent#137]
Hello,

I can't figure it out why is this config failing:

```
mongodb:
    name: localhost
    host: localhost
    port: 27017
    admin_username: admin
    admin_password: password
    databases:
      db1:
        username: user1
        password: password
```

I get the following error when starting the agent:

$ newrelic_plugin_agent -c /etc/newrelic/newrelic_plugin_agent.cfg -f
INFO       2013-09-03 10:36:54 27927  MainProcess     MainThread clihelper                                     run                       L382   : newrelic_plugin_agent 1.1.0 started
Exception: OperationFailure(u"command SON([('authenticate', 1), ('user', u'admin'), ('nonce', u'96c5679be83f59c0'), ('key', u'MY_KEY')]) failed: auth fails",)

but the connection works from the command line:

$ mongo localhost:27017/admin -u admin -p password
MongoDB shell version: 2.2.2
connecting to: localhost:27017/admin
'>' exit
bye

$ mongo localhost:27017/db1 -u user1 -p password
MongoDB shell version: 2.2.2
connecting to: localhost:27017/db1
'>' exit
bye

Isn't the admin user supposed to authenticate against the admin database or am I missing something?

Thanks in advance for your help.
