### ISSUE TITLE
Inconsistent results in Newrelic MongoDB monitoring

### ISSUE THREAD

**Issue by igoratencompass** [MeetMe/newrelic-plugin-agent#141]
Hi all,

I'm receiving inconsistent results in Newrelic using this plugin. I have the following configuration on couple of hosts running 2 mongo databases each, db1 on port 27017 and db2 on port 27018:

```
mongodb:
  - name: host1
    host: localhost
    port: 27017
    admin_username: admin
    admin_password: password
    databases:
      db1:
        username: user1
        password: password
  - name: host1
    host: localhost
    port: 27018
    admin_username: admin
    admin_password: password
    databases:
      db2:
        username: user2
        password: password
```

The second server has the same config with host2 instead host1 in the file.

For the first server, both databases are displayed under same host in Newrelic called  host1. But for the second server I get 2 hosts in Newrelic, one called host2 with db1 inside and another one with the server's (short not the FQDN) host name with db2 inside. Both servers have the default /etc/hosts file with only localhost inside.

Any idea what might be the cause of these? Can you spot anything wrong in my config?

Thanks,
Igor
