### ISSUE TITLE
Agent works well with php-fpm on some servers but not others.

### ISSUE THREAD

**Issue by ian-lewis-cs** [MeetMe/newrelic-plugin-agent#142]
I have the agent running on a couple of servers successfully sending back data to NR. However with a similar config on two other servers in the cluster there is no data being returned to NR although the agent is running.

I have cross checked the configs and all look Ok. nginx is set up correctly to return the  php-fpm status page and I have verified this with $ lynx http://localhost/php-fpm-status

Suggestions please..

**Comment by rfay** [comment]
I have what I think is exactly the same problem, and the issue is that php5-fpm is closing the connection, and I haven't figured out why. 

```
ERROR      2015-05-29 11:34:16,774 9578   MainProcess     MainThread newrelic_plugin_agent.plugins.base            http_get                  L349   : Error polling stats: ('Connection aborted.', error(104, 'Connection reset by peer'))
ERROR      2015-05-29 11:34:16,774 9578   MainProcess     MainThread newrelic_plugin_agent.plugins.base            error_message             L128   : Error collecting stats data from FPM. Please check configuration and sure it conforms with YAML syntax
```

I'm on Ubuntu 12.04, current newrelic-plugin 1.3.0, current newrelic libraries. 

```
  php_fpm:
    - name: fpm-pool
      scheme: http
      host: 127.0.0.1
      port: 9000
      path: status
      query: json
```

I'm able to query http://127.0.0.1:9000/status?json just fine using
`SCRIPT_NAME=/status SCRIPT_FILENAME=/status QUERY_STRING=json REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000`

However, I cannot query it with curl or lynx (I get the same "Connection reset by peer" that the plugin-agent is getting in this situation.

**Comment by rfay** [comment]
Probably the same as #300

**Comment by rfay** [comment]
I have worked around this by configuring nginx to front-end php5-fpm instead of having the agent go to it directly. That way the cgi scheme is properly done. Of course, it relies on nginx being alive and well.

I just used the technique in https://rtcamp.com/tutorials/php/fpm-status-page/ allowing access via nginx (and only to localhost). I added this into the "default" host config for localhost.

Then:
```
php_fpm:
    - name: pool
      scheme: http
      host: localhost
      port: 80
      path: status
      query: json
```
