### ISSUE TITLE
php-fpm plugin not sending stats to NR

### ISSUE THREAD

**Issue by jeremygamma** [MeetMe/newrelic-plugin-agent#150]
Trying to set up the php-fpm plugin on one of our webservers, and we're not getting stats sent to newrelic.  All that appears in the log file is:

```
INFO       2013-09-19 12:47:37 27083  MainProcess     MainThread newrelic_plugin_agent.agent                   process                   L93    : Polling
INFO       2013-09-19 12:47:37 27083  MainProcess     MainThread newrelic_plugin_agent.agent                   send_components           L176   : Sending 0 metrics to NewRelic
INFO       2013-09-19 12:47:37 27083  MainProcess     MainThread newrelic_plugin_agent.agent                   process                   L107   : All stats processed in 0.13 seconds, next wake in 59.87
```

Config file looks perfect according to the docs:

```
%YAML 1.2

---
Application:
  license_key: {hidden}
  poll_interval: 60

  php_fpm:
    name: fpm-pool
    scheme: http
    host: {hostname}
    port: 80
    path: /fpm-status
    query: json

Daemon:
  user: newrelic
  pidfile: /var/run/newrelic/newrelic_plugin_fpm_agent.pid

Logging:
  formatters:
    verbose:
      format: '%(levelname) -10s %(asctime)s %(process)-6d %(processName) -15s %(threadName)-10s %(name) -45s %(funcName) -25s L%(lineno)-6d: %(message)s'
  handlers:
    file:
      class : logging.handlers.RotatingFileHandler
      formatter: verbose
      filename: /var/log/newrelic/newrelic_plugin_fpm_agent.log
      maxBytes: 10485760
      backupCount: 3
  loggers:
    newrelic_plugin_agent:
      level: INFO
      propagate: True
      handlers: [console, file]
    requests:
      level: ERROR
      propagate: True
      handlers: [console, file]
```

I can curl the fpm-status page directly:

```
[root@{hostname} newrelic]# curl http://{hostname}/fpm-status?json
{"pool":"www","process manager":"dynamic","start time":1379601317,"start since":8220,"accepted conn":115299,"listen queue":0,"max listen queue":23,"listen queue len":128,"idle processes":33,"active processes":2,"total processes":35,"max active processes":42,"max children reached":0,"slow requests":0}
```
