### ISSUE TITLE
Does the apache monitor support individual and cumulative stats?

### ISSUE THREAD

**Issue by ChrisFullerton** [MeetMe/newrelic-plugin-agent#174]
I have been experimenting with having individual and cumulative stats by including two apache_httpd stanzas with different names, similar to:

```
    apache_httpd:
        name: node-1
        scheme: http
        host: localhost
        verify_ssl_cert: false
        port: 80
        path: /server-status

     apache_httpd:
        name: totals
        scheme: http
        host: localhost
        verify_ssl_cert: false
        port: 80
        path: /server-status
```

This is running on multiple load balanced instances, but doesn't seem to work.  Is this supported?
