### ISSUE TITLE
Is it possible to monitor more than once instance of redis running on the same host from a single agent instance?

### ISSUE THREAD

**Issue by arievlognow** [MeetMe/newrelic-plugin-agent#24]

**Comment by ko-christ** [comment]
@gmr is monitoring of Redis Clusters supported?
I can see some cluster related metrics like this `'Component/Slaves/Connected[slaves]'`.
Is it supported/suggested to configure _different_ Redis nodes of the _same_ cluster using the same `name` for NewRelic or not? For example

```
redis:
    # redis_cluster_01
    - name: redis_cluster_01
      host: localhost
      port: 6379
      db_count: 1
      password: foobar
    - name: redis_cluster_01
      host: localhost
      port: 6380
      db_count: 1
      password: foobar

    # redis_cluster_02
    - name: redis_cluster_02
      host: localhost
      port: 6381
      db_count: 1
      password: foobar
    - name: redis_cluster_02
      host: localhost
      port: 6382
      db_count: 1
      password: foobar
```
