### ISSUE TITLE
agent dies when postgresql plugin is enabled

### ISSUE THREAD

**Issue by davewo** [MeetMe/newrelic-plugin-agent#323]
When I enable the postgresql plugin in the agent config (below), the plugin will die after a period of time (latest attempt was approximately 6 hours).  The agent is running on a CentOS 6 machine.  Nothing useful is given in /var/log/messages or dmesg about the process being killed.

The agent ran fine all weekend with the postgresql plugin disabled.  I am now gathering agent logs with level: DEBUG and postgresql enabled, and will report back with the logs when the agent dies again.

```
%YAML 1.2

---
Application:
  license_key:
  wake_interval: 60

  apache_httpd:
    - name: vresults
      scheme: http
      host: vresults
      port: 80
      path: /server-status
    - name: vweb
      scheme: http
      host: vweb-us
      port: 80
      path: /server-status

  mongodb:
    - name: cnode3-times-cache
      host: cnode3
      port: 27017
      ssl: False
      databases:
        - results
        - results-au
    - name: cnode2-times-cache
      host: cnode2
      port: 27017
      ssl: False
      databases:
        - results
        - results-au
    - name: cnode1-times-cache
      host: cnode1
      port: 27017
      ssl: False
      databases:
        - results
        - results-au

  nginx:
    - name: touchpadlive
      scheme: http
      host: vr1nginx
      port: 80
      path: /nginx_stub_status
    - name: touchpadlive-au
      scheme: http
      host: vr2nginx
      port: 80
      path: /nginx_stub_status
    - name: swimtoday
      scheme: http
      host: vswimtoday
      port: 8888
      path: /nginx_stub_status

Daemon:
  user: newrelic
  pidfile: /var/run/newrelic/newrelic-plugin-agent.pid

Logging:
  formatters:
    verbose:
      format: '%(levelname) -10s %(asctime)s %(process)-6d %(processName) -15s %(threadName)-10s %(name) -45s %(funcName) -25s L%(lineno)-6d: %(message)s'
  handlers:
    file:
      class : logging.handlers.RotatingFileHandler
      formatter: verbose
      filename: /var/log/newrelic/newrelic-plugin-agent.log
      maxBytes: 10485760
      backupCount: 3
  loggers:
    newrelic_plugin_agent:
      level: DEBUG
      propagate: True
      handlers: [console, file]
    requests:
      level: ERROR
      propagate: True
      handlers: [console, file]
```
