### ISSUE TITLE
redis issue

### ISSUE THREAD

**Issue by alienzrcoming** [MeetMe/newrelic-plugin-agent#35]
Hi,

I have a redis instance that I am trying to monitor, but am getting the following error when running '/usr/local/bin/newrelic_plugin_agent -c /etc/newrelic_plugin_agent.yml -f'

--snip
INFO       2013-06-20 15:57:29 8355   MainProcess     MainThread clihelper                                     run                       L382   : newrelic_plugin_agent 1.0.11 started
INFO       2013-06-20 15:57:29 8355   MainProcess     MainThread newrelic_plugin_agent.agent                   process                   L91    : Polling
INFO       2013-06-20 15:57:29 8355   MainProcess     MainThread newrelic_plugin_agent.plugins.redis           poll                      L219   : Polling Redis
Exception: AttributeError("'str' object has no attribute 'get'",)

Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/clihelper/**init**.py", line 742, in run
    process.run()
  File "/usr/local/lib/python2.6/dist-packages/clihelper/**init**.py", line 384, in run
    self.process()
  File "/usr/local/lib/python2.6/dist-packages/newrelic_plugin_agent/agent.py", line 93, in process
    self.start_plugin_polling()
  File "/usr/local/lib/python2.6/dist-packages/newrelic_plugin_agent/agent.py", line 255, in start_plugin_polling
    self.application_config.get(plugin))
  File "/usr/local/lib/python2.6/dist-packages/newrelic_plugin_agent/agent.py", line 82, in poll_plugin
    thread.run()
  File "/usr/lib/python2.6/threading.py", line 484, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/local/lib/python2.6/dist-packages/newrelic_plugin_agent/agent.py", line 274, in thread_process
    obj.poll()
  File "/usr/local/lib/python2.6/dist-packages/newrelic_plugin_agent/plugins/redis.py", line 231, in poll
    connection = self.connect(server)
  File "/usr/local/lib/python2.6/dist-packages/newrelic_plugin_agent/plugins/redis.py", line 145, in connect
    params = (config.get('host', self.DEFAULT_HOST),
AttributeError: 'str' object has no attribute 'get'
--snip

my /etc/newrelic_plugin_agent.yml looks like this:

```
%YAML 1.2

---
Application:
  license_key: secret
  poll_interval: 60


  redis:
    name: host1
    host: localhost
    port: 6379
    db_count: 16
    password: 




Daemon:
  pidfile: /var/run/newrelic_plugin_agent.pid

Logging:
  formatters:
    verbose:
      format: '%(levelname) -10s %(asctime)s %(process)-6d %(processName) -15s %(threadName)-10s %(name) -45s %(funcName) -25s L%(lineno)-6d: %(message)s'
  handlers:
    file:
      class : logging.handlers.RotatingFileHandler
      formatter: verbose
      filename: /var/log/newrelic/newrelic_plugin_agent.log
      maxBytes: 10485760
      backupCount: 3
  loggers:
    newrelic_plugin_agent:
      level: INFO
      propagate: True
      handlers: [console, file]
    requests:
      level: ERROR
      propagate: True
      handlers: [console, file]
```

i can connect to redis using the cli and all that, so my daemon is responding.  am i missing something obvious?  thanks in advance

debian squeeze 6.0.6
newrelic-plugin-agent==1.0.11
