### ISSUE TITLE
How to define multiple MongoDB connections?

### ISSUE THREAD

**Issue by tclancy** [MeetMe/newrelic-plugin-agent#354]
I have a configuration setup like this:

```
  mongodb:
    name: mongo-1.client.com
    host: mongo-1.client.com
    port: 27017
    databases:
      - db_1
      - db_2
      - db_3
    name: mongo-2.client.com
    host: mongo-2.client.com
    port: 27017
    databases:
      - db_1
      - db_2
      - db_3
    name: mongo-3.client.com
    host: mongo-3.client.com
    port: 27017
    databases:
      - db_1
      - db_2
      - db_3
    name: mongo-4.client.com
    host: mongo-4.client.com
    port: 27017
    databases:
      - some_different_db
```

Running with this configuration, the only Mongo instance the agent reports on is the one defined last in the file. Do I have the indentation wrong or is this not possible?
