### ISSUE TITLE
params question

### ISSUE THREAD

**Issue by rlex** [MeetMe/newrelic-plugin-agent#366]
Hello, i'm writing puppet module for newrelic-plugin-agent, got a couple of questions.

On some params i see 

```
verify_ssl_cert: true
```

As bool, with downcase leading symbol.
While on another, i see

```
superuser: False
```

This looks like sting with uppercase leading symbol?
Does this matter or both (uppercase/downcase) variants will work?

Another question:
Can i define several instances of one service like

``` yaml
  php_fpm:
    - name: fpm-pool
      scheme: https
      host: localhost
      port: 443
      path: /fpm_status
      query: json
  php_fpm:
    - name: fpm-pool
      scheme: https
      host: localhost
      port: 443
      path: /fpm_status
      query: json
```

Or that will not work and i need to define them under single php_fpm block?
