### ISSUE TITLE
How to monitor multiple Memcached servers?

### ISSUE THREAD

**Issue by gcobr** [MeetMe/newrelic-plugin-agent#368]
I tried to configure multiple Memcached servers by putting multiple blocks of settings in the file, like this:

```
memcached:
    name: AnApplication
    host: host-of-memcachedserver1
    port: 11211

memcached:
    name: AnotherApplication
    host: host-of-memcachedserver2
    port: 11211
```

But MeetMe is only collecting data for the last entry ('AnotherApplication' above).

Is it not possible to monitor multiple Memcached servers?

Should I try to run multiple instances of the agent with different configuration files, one for each Memcached server?
