### ISSUE TITLE
How to monitor a MongoDB replicaset?

### ISSUE THREAD

**Issue by gcobr** [MeetMe/newrelic-plugin-agent#369]
I am trying to monitor a MongoDB replicaset, and to accomplish this I tried to add one 'mongodb' configuration block in the file for each of the nodes.

```
  mongodb:
    name: MyNode1
    host: node1.domain
    port: 27017
    databases:
      - dbA
      - dbB

  mongodb:
    name: MyNode2
    host: node2.domain
    port: 27017
    databases:
      - dbA
      - dbB

  mongodb:
    name: MyNode3
    host: node3.domain
    port: 27017
    databases:
      - dbA
      - dbB
```

The agent is, however, only sending information about the node configured in the last block.

Should I configure this differently? Should I try to run one instance of the agent for each MongoDB node of my replicaset?

I guess my attempt must be wrong because it doens't make much sense to have multiple 'databases' blocks mentioning the same databases.
