### ISSUE TITLE
Just trying to run

### ISSUE THREAD

**Issue by richwandell** [MeetMe/newrelic-plugin-agent#381]
I get this message can you help me figure out whats going on?

[root@localhost newrelic-plugin-agent-master]# newrelic-plugin-agent -c config.yaml -f
INFO       2015-01-22 16:24:35,186 6450   MainProcess     MainThread helper.controller         run                       L251   : newrelic-plugin-agent v2.4.1 started
Traceback (most recent call last):
  File "/usr/bin/newrelic-plugin-agent", line 9, in <module>
    load_entry_point('newrelic-plugin-agent==1.3.0', 'console_scripts', 'newrelic-plugin-agent')()
  File "build/bdist.linux-x86_64/egg/newrelic_plugin_agent/agent.py", line 337, in main
  File "build/bdist.linux-x86_64/egg/helper/__init__.py", line 174, in start
  File "build/bdist.linux-x86_64/egg/helper/controller.py", line 266, in start
  File "build/bdist.linux-x86_64/egg/helper/controller.py", line 253, in run
  File "build/bdist.linux-x86_64/egg/newrelic_plugin_agent/agent.py", line 125, in process
  File "build/bdist.linux-x86_64/egg/newrelic_plugin_agent/agent.py", line 209, in send_data_to_newrelic
  File "build/bdist.linux-x86_64/egg/newrelic_plugin_agent/agent.py", line 230, in send_components
  File "/usr/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 518, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 322, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg/requests/packages/urllib3/connectionpool.py", line 727, in _validate_conn
    conn.connect()
  File "/usr/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg/requests/packages/urllib3/util/ssl_.py", line 254, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/lib64/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 537, in __init__
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

**Comment by fredrikmollerstrand** [comment]
Could you paste your `config.yaml`?

**Comment by gmr** [comment]
(and remove your API key when doing so)

**Comment by cog-piisang** [comment]
ValueError: check_hostname requires server_hostname

**Comment by richwandell** [comment]
```
%YAML 1.2
---
Application:
  license_key: thekey
  poll_interval: 60
  #newrelic_api_timeout: 10
  #proxy: http://localhost:8080

  redis:
    - name: localhost
      host: localhost
      port: 6379
      db_count: 16


Daemon:
  user: newrelic
  pidfile: /var/run/newrelic/newrelic-plugin-agent.pid

Logging:
  formatters:
    verbose:
      format: '%(levelname) -10s %(asctime)s %(process)-6d %(processName) -15s %(threadName)-10s %(name) -25s %(funcName) -25s L%(lineno)-6d: %(message)s'
  handlers:
    file:
      class : logging.handlers.RotatingFileHandler
      formatter: verbose
      filename: /var/log/newrelic/newrelic-plugin-agent.log
      maxBytes: 10485760
      backupCount: 3
  loggers:
    newrelic-plugin-agent:
      level: INFO
      propagate: True
      handlers: [console, file]
    requests:
      level: ERROR
      propagate: True
      handlers: [console, file]
```
