### ISSUE TITLE
Postgres: remove duplicates from New Relic plugin inventory

### ISSUE THREAD

**Issue by dsavinkov** [MeetMe/newrelic-plugin-agent#386]
Hello,
I have completed setup of **newrelic-plugin-agent** for our Postgres servers without ***name*** parameter in ***.cfg*** file. Later, I added this parameter to YAML file and restarted plugin. Instead of displaying only one "changed" instance it shows 2 server monitoring stats with both old (IP name) and new actual server name. Could you please assist in resolving this?  
```yaml
postgresql:
          name: <ServerName>
          host: localhost
          port: 5432
          user: postgres
          dbname: postgres
          superuser: True
```
Thank you in advance,
Dmitry
