### ISSUE TITLE
Error on start: no handlers could be found for logger...

### ISSUE THREAD

**Issue by dylancwood** [MeetMe/newrelic-plugin-agent#423]
Thanks for writing and maintaining this plugin. I am experiencing a problem when starting the plugin, and hope that someone can help me to resolve it. Thank you in advance.

## Background
* OS: Ubuntu14.04
* Python version: 2.7.6
* pip version: 7.0.3

## Command used:
```
sudo -u newrelic newrelic-plugin-agent -f -c /coins/meetme_newrelic_plugin_agent_conf.yaml
```
## Expected output:
```
INFO       2015-06-17 12:48:39,850 9487   MainProcess     MainThread helper.controller         run                       L251   : newrelic-plugin-agent v2.4.1 started
```

## Actual output:
```
dwood@stagedbcoin:~$ sudo -u newrelic newrelic-plugin-agent -f -c /coins/meetme_newrelic_plugin_agent.conf 
INFO       2015-06-17 12:48:39,850 9487   MainProcess     MainThread helper.controller         run                       L251   : newrelic-plugin-agent v2.4.1 started
No handlers could be found for logger "newrelic_plugin_agent.plugins.postgresql"
```

## Discussion:
No info is being written to the log specified in my conf file (see below). I am also not seeing anything new pop up on the newrelic dashboard.

## My conf file:
```
%YAML 1.2 
---
Application:
  license_key: (hidden)
  wake_interval: 60
  postgresql:
    host: localhost
    port: 5432
    user: ni_developers
    dbname: postgres
    password: (hidden)
    superuser: True
    relation_stats: True
Daemon:
  user: newrelic
  pidfile: /var/run/newrelic/newrelic-plugin-agent.pid

Logging:
  formatters:
    verbose:
      format: '%(levelname) -10s %(asctime)s %(process)-6d %(processName) -15s %(threadName)-10s %(name) -25s %(funcName) -25s L%(lineno)-6d: %(message)s'
  handlers:
    file:
      class : logging.handlers.RotatingFileHandler
      formatter: verbose
      filename: /var/log/newrelic/newrelic-plugin-agent.log
      maxBytes: 10485760
      backupCount: 3
  loggers:
    newrelic-plugin-agent:
      level: INFO
      propagate: True
      handlers: [console, file]
    requests:
      level: ERROR
      propagate: True
      handlers: [console, file]
```
