### ISSUE TITLE
support for multiple entries for services

### ISSUE THREAD

**Issue by nand0p** [MeetMe/newrelic-plugin-agent#43]
im trying to have multiple entries for a single service, such as:

```
Application:
  license_key: XXX
  poll_interval: 60

  apache_httpd:
    name: test1
    host: 10.0.0.1
    port: 80
    path: /status

  apache_httpd:
    name: test2
    host: 10.0.0.2
    port: 80
    path: /status
```

only the first entry registers with newrelic.  is there a way to do this, so as to have a centralized newrelic monitoring box, (as opposed to having to run plugin on each machine, or having seperate newrelic_plugin proc for each service instance)

thanks,
.fjp
