### ISSUE TITLE
How to use (expand) environment variables in configuration files?

### ISSUE THREAD

**Issue by pataquets** [MeetMe/newrelic-plugin-agent#434]
I would like to deploy NRPA as a sidekick Docker container. I would like to include a previously configured .cfg, and and the best solutoin would be to expand environment variables when reading the configuration file.

What I've tried after googling, so far:
```
Application:
  license_key: <%= ENV['NEWRELIC_KEY'] %>
  license_key: ENV['NEWRELIC_KEY']
  license_key: $NEWRELIC_KEY
```
Is there any way?
TIA.
