### ISSUE TITLE
Redis plugin for monitoring

### ISSUE THREAD

**Issue by ipeacocks** [MeetMe/newrelic-plugin-agent#484]
What is `db_count: 16` in redis plugin configuration?

```
  redis:
    - name: example.com
      host: localhost
      port: 6379
      db_count: 16
```
