### ISSUE TITLE
Meetme Plugin Error -  No metrics to send to NewRelic this interval

### ISSUE THREAD

**Issue by JustGithub1** [MeetMe/newrelic-plugin-agent#553]
We have installed the Meetme plugin and it is not started. Received error below. Appreciate any suggestion to resolve the issue.

Thank you,
JP

INFO       2018-05-23 13:44:13,255 33     MainProcess     MainThread newrelic_plugin_agent.agent                   __init__                  L55    : Agent v1.3.0 initialized, Linux-4.4.0-43-Microsoft-x86_64-with-glibc2.7 (Ubuntu 16.04 xenial) CPython v2.7.12
INFO       2018-05-23 13:44:13,256 33     MainProcess     MainThread helper.controller                             run                       L251   : newrelic-plugin-agent v2.4.2 started
WARNING    2018-05-23 13:44:13,256 33     MainProcess     MainThread newrelic_plugin_agent.agent                   send_components           L217   : No metrics to send to NewRelic this interval
INFO       2018-05-23 13:44:13,256 33     MainProcess     MainThread newrelic_plugin_agent.agent                   process                   L133   : Stats processed in 0.00 seconds, next wake in 59 seconds
WARNING    2018-05-23 13:45:13,257 33     MainProcess     MainThread newrelic_plugin_agent.agent                   send_components           L217   : No metrics to send to NewRelic this interval
INFO       2018-05-23 13:45:13,260 33     MainProcess     MainThread newrelic_plugin_agent.agent                   process                   L133   : Stats processed in 0.00 seconds, next wake in 59 seconds

**Comment by doreplado** [comment]
@Jackpham6407 try setting the cfg log-level to DEBUG for requests and the agent. I had a similar issue where my license key had a typo and I didn't know until I turned on debug.

**Comment by hansgv** [comment]
I have a similar issue (running Ubuntu 18.04). Rising the log levels to debug doesn't provide any additional information. My conf is pretty simple. The conf URLs (http:/127.0.0.1:80/nginx_status , http:/127.0.0.1:80/status-php56 and http:/127.0.0.1:80/status-php72 all respond)

```
nginx:
    name: my.hostname.here
    scheme: http
    host: 127.0.0.1
    port: 80
    path: /nginx_status

php_fpm:
  - name: fpm56-pool
    scheme: http
    host: 127.0.0.1
    port: 80
    path: /status-php56
    query: json
  - name: fpm72-pool
    scheme: http
    host: 127.0.0.1
    port: 80
    path: /status-php72
    query: json

```
