### ISSUE TITLE
CouchDB auth broken

### ISSUE THREAD

**Issue by Overtorment** [MeetMe/newrelic-plugin-agent#58]
It used to work like this

```
  couchdb:
    name: myname
    host: admin:password@localhost
    port: 5984
```

but latest install on new VDS throws

```
 Error response from http://admin:password@localhost:5984/_stats (401): {"error":"unauthorized","reason":"Authentication required."}
```
